name: build-windows-manual

on:
  workflow_dispatch:  # permite execução manual

jobs:
  build:
    runs-on: windows-latest  # aqui é o runner Windows
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Exibir informações do sistema
        run: systeminfo

      - name: Compilar (exemplo)
        run: |
          echo "Rodando em ambiente Windows"
          dir

      
 

